package com.skeleton.home;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import android.text.*;
import android.text.method.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;

public final class MainActivity extends Activity {
  // TEST CANDIDATE: visual parity is gated against the canonical web design; SK is the Skeleton Dashboard pilot.
  static final String VERSION="1.3.1";
  static final int BG=Color.rgb(10,13,16), CARD=Color.rgb(21,26,31), CARD2=Color.rgb(26,32,38), TILE=Color.rgb(18,23,28), ACTION=Color.rgb(23,29,35), INPUT=Color.rgb(17,22,26), LINE=Color.rgb(35,42,49), TEXT=Color.rgb(245,246,247), MUTED=Color.rgb(141,150,159), ACCENT=Color.rgb(255,106,0), ACCENT_SOFT=Color.rgb(42,28,19), GREEN=Color.rgb(88,213,123); // exact ui.css :root tokens
  static final String[] SERVERS={"http://home-edge.local:8100"};
  final Handler ui=new Handler(); final ExecutorService net=Executors.newFixedThreadPool(3); volatile String server=null; boolean resumed=false;
  LinearLayout root,nav; FrameLayout content; View[] screens=new View[4]; Button[] navButtons=new Button[4]; int current=0; Runnable poller; final String[] NAV_ICONS={"home","movie-open","monitor-dashboard","devices"}; final String[] NAV_NAMES={"Головна","Відео","СК","Пристрої"};
  TextView conn; final ArrayList<TextView> connViews=new ArrayList<TextView>(); final ArrayList<ImageView> hyperionBulbs=new ArrayList<ImageView>(); final ArrayList<NativeSwitch> hyperionSwitches=new ArrayList<NativeSwitch>(); boolean hyperionOn=false,hyperionBusy=false;
  // Home
  TextView homeTitle,homeMeta,homePos,homeDur,homeVol; AspectImageView homePoster; FrameLayout homeVisual; YoutubeNavPanel homeYoutubePanel; LinearLayout homeTvPanel,homeTransport,homeTimeRow; SkeletonSlider homeSeek,homeVolume; String homePosterUrl="",currentHomeMode=""; Button[] modeButtons=new Button[4]; ImageButton[] transportButtons=new ImageButton[4]; String homeSnapshot="";
  // Video
  TextView videoTitle,videoMeta,videoOverview,videoMsg; AspectImageView videoPoster; SkeletonSelect seasonSp,episodeSp,qualitySp,voiceSp; Button historyBtn,applyBtn,resetBtn; SkeletonToggle autoplay; LinearLayout providerRow; ImageButton traktBtn,moviebaseBtn; JSONObject videoJob,videoSelection; JSONArray videoSources=new JSONArray(); String currentJob="",videoPosterUrl=""; boolean spinnerBusy=false;
  // SK
  LinearLayout skList; String skSnapshot="";
  // Devices
  LinearLayout devicesList; String devicesSnapshot="";

  interface JsonCb { void done(JSONObject j, Exception e); }
  @Override public void onCreate(Bundle b){setTheme(android.R.style.Theme_Black_NoTitleBar);super.onCreate(b);buildApp();discover();handleIntent(getIntent());}
  @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handleIntent(i);}
  @Override protected void onResume(){super.onResume();resumed=true;schedulePoll(50);}
  @Override protected void onPause(){resumed=false;if(poller!=null)ui.removeCallbacks(poller);super.onPause();}
  @Override protected void onDestroy(){net.shutdownNow();super.onDestroy();}

  int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
  void sizePx(TextView t,float px){t.setTextSize(android.util.TypedValue.COMPLEX_UNIT_DIP,px);}
  Typeface regular(){return Typeface.create("sans-serif",Typeface.NORMAL);} Typeface medium(){return Typeface.create("sans-serif-medium",Typeface.NORMAL);}
  TextView tv(String text,float px,int color){TextView t=new TextView(this);t.setText(text);sizePx(t,px);t.setTextColor(color);t.setTypeface(regular());t.setGravity(Gravity.CENTER_VERTICAL);t.setIncludeFontPadding(false);return t;}
  void weight(TextView t,int w){t.setTypeface(w>=600?medium():regular());}
  GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));g.setStroke(dp(1),LINE);return g;}
  GradientDrawable flat(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
  void pad(View v,int a){v.setPadding(dp(a),dp(a),dp(a),dp(a));}
  LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
  void addSpace(LinearLayout p,int h){Space x=new Space(this);p.addView(x,new LinearLayout.LayoutParams(1,dp(h)));}
  void setText(TextView v,String x){if(v!=null&&!String.valueOf(v.getText()).equals(x))v.setText(x);}
  String fmt(double sec){int z=(int)Math.max(0,sec),h=z/3600,m=(z%3600)/60,ss=z%60;return h>0?String.format(Locale.US,"%d:%02d:%02d",h,m,ss):String.format(Locale.US,"%d:%02d",m,ss);}
  String opt(JSONObject j,String k,String d){String x=j==null?null:j.optString(k,null);return x==null||x.length()==0?d:x;}
  Drawable icon(String name,int size,int color){try{InputStream in=getAssets().open("native-icons/"+name+".png");Bitmap b=BitmapFactory.decodeStream(in);in.close();BitmapDrawable d=new BitmapDrawable(getResources(),b);d.setBounds(0,0,dp(size),dp(size));d.setColorFilter(color,PorterDuff.Mode.SRC_IN);return d;}catch(Exception e){return new ColorDrawable(Color.TRANSPARENT);}}
  ImageView iconView(String name,int size,int color){ImageView v=new ImageView(this);v.setScaleType(ImageView.ScaleType.CENTER);v.setImageDrawable(icon(name,size,color));return v;}
  ImageButton iconButton(String name,int size,int color,int touch){ImageButton b=new ImageButton(this);b.setScaleType(ImageView.ScaleType.CENTER);b.setImageDrawable(icon(name,size,color));b.setBackgroundColor(Color.TRANSPARENT);b.setPadding(0,0,0,0);b.setMinimumWidth(0);b.setMinimumHeight(0);b.setLayoutParams(new ViewGroup.LayoutParams(dp(touch),dp(touch)));return b;}
  Button button(String label){Button b=new Button(this);b.setText(label);b.setTextColor(TEXT);sizePx(b,11);weight(b,700);b.setAllCaps(false);b.setBackgroundDrawable(bg(ACTION,11));b.setPadding(dp(8),0,dp(8),0);b.setMinWidth(0);b.setMinHeight(0);return b;}
  Button iconTextButton(String label,String iconName,int iconSize,float textPx,int color){Button b=new Button(this);b.setText(label);sizePx(b,textPx);b.setTextColor(color);weight(b,600);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackgroundColor(Color.TRANSPARENT);b.setCompoundDrawables(null,icon(iconName,iconSize,color),null,null);b.setCompoundDrawablePadding(dp(3));b.setPadding(0,0,0,0);b.setMinWidth(0);b.setMinHeight(0);b.setIncludeFontPadding(false);return b;}
  void styleNav(int i,boolean active){Button b=navButtons[i];int c=active?ACCENT:MUTED;b.setTextColor(c);weight(b,active?700:600);b.setCompoundDrawables(null,icon(NAV_ICONS[i],21,c),null,null);}
  static final class AspectImageView extends ImageView {float rw=2f,rh=3f;AspectImageView(Context c){super(c);setScaleType(ScaleType.CENTER_CROP);}void ratio(float w,float h){rw=w;rh=h;requestLayout();}@Override protected void onMeasure(int ws,int hs){int aw=MeasureSpec.getSize(ws),ah=MeasureSpec.getSize(hs);if(aw<=0||ah<=0){super.onMeasure(ws,hs);return;}int w=aw,h=(int)(w*rh/rw);if(h>ah){h=ah;w=(int)(h*rw/rh);}setMeasuredDimension(Math.max(1,w),Math.max(1,h));}}
  final class NativeSwitch extends FrameLayout {View thumb;boolean checked;NativeSwitch(){super(MainActivity.this);setPadding(dp(3),dp(3),dp(3),dp(3));thumb=new View(MainActivity.this);thumb.setBackgroundDrawable(flat(Color.WHITE,99));addView(thumb,new FrameLayout.LayoutParams(dp(18),dp(18)));setChecked(false);setOnClickListener(v->setHyperion(!checked));}void setChecked(boolean c){checked=c;setBackgroundDrawable(flat(c?ACCENT:Color.rgb(65,73,82),99));thumb.setTranslationX(c?dp(18):0);}}
  interface SliderListener { void changed(int value, boolean fromUser); void stopped(int value); }
  final class SkeletonSlider extends View {
    Paint track=new Paint(Paint.ANTI_ALIAS_FLAG),fillPaint=new Paint(Paint.ANTI_ALIAS_FLAG),thumbPaint=new Paint(Paint.ANTI_ALIAS_FLAG); int max=100,progress=0; SliderListener listener;
    SkeletonSlider(){super(MainActivity.this);track.setColor(Color.rgb(52,59,66));fillPaint.setColor(ACCENT);thumbPaint.setColor(Color.WHITE);setFocusable(true);}
    void setMax(int m){max=Math.max(1,m);progress=Math.min(progress,max);invalidate();} int getProgress(){return progress;} void setProgress(int v){progress=Math.max(0,Math.min(max,v));invalidate();}
    void setOnValueListener(SliderListener l){listener=l;}
    @Override protected void onDraw(Canvas c){super.onDraw(c);float den=getResources().getDisplayMetrics().density,r=7.5f*den,h=4f*den,y=getHeight()/2f,x0=r,x1=Math.max(x0,getWidth()-r),f=max<=0?0f:(progress/(float)max),xp=x0+(x1-x0)*f;track.setStrokeWidth(h);track.setStrokeCap(Paint.Cap.ROUND);fillPaint.setStrokeWidth(h);fillPaint.setStrokeCap(Paint.Cap.ROUND);c.drawLine(x0,y,x1,y,track);c.drawLine(x0,y,xp,y,fillPaint);c.drawCircle(xp,y,r,thumbPaint);}
    int valueAt(float x){float den=getResources().getDisplayMetrics().density,r=7.5f*den,x0=r,x1=Math.max(x0+1,getWidth()-r),f=Math.max(0f,Math.min(1f,(x-x0)/(x1-x0)));return Math.round(f*max);}
    @Override public boolean onTouchEvent(android.view.MotionEvent e){if(!isEnabled())return false;int a=e.getActionMasked();if(a==android.view.MotionEvent.ACTION_DOWN||a==android.view.MotionEvent.ACTION_MOVE){setPressed(true);setProgress(valueAt(e.getX()));if(listener!=null)listener.changed(progress,true);return true;}if(a==android.view.MotionEvent.ACTION_UP||a==android.view.MotionEvent.ACTION_CANCEL){if(a==android.view.MotionEvent.ACTION_UP){setProgress(valueAt(e.getX()));if(listener!=null){listener.changed(progress,true);listener.stopped(progress);}}setPressed(false);return true;}return true;}
  }
  interface SelectListener { void selected(SkeletonSelect view); }
  final class SkeletonSelect extends TextView {
    ArrayList<String> values=new ArrayList<String>(); int selected=-1; SelectListener listener;
    SkeletonSelect(){super(MainActivity.this);setTextColor(TEXT);sizePx(this,14);weight(this,500);setGravity(Gravity.CENTER_VERTICAL);setIncludeFontPadding(false);setPadding(dp(10),0,dp(9),0);setBackgroundDrawable(bg(INPUT,9));setCompoundDrawables(null,null,icon("chevron-down",16,MUTED),null);setCompoundDrawablePadding(dp(6));setOnClickListener(v->openList());}
    void setOnSelected(SelectListener l){listener=l;} String value(){return selected>=0&&selected<values.size()?values.get(selected):"";}
    void setOptions(List<String> vals,String wanted){values.clear();values.addAll(vals);selected=-1;if(wanted!=null)selected=values.indexOf(wanted);if(selected<0&&values.size()>0)selected=0;setText(value());setEnabled(values.size()>0);setAlpha(values.size()>0?1f:.55f);}
    void openList(){if(values.isEmpty())return;final Dialog d=new Dialog(MainActivity.this);LinearLayout box=new LinearLayout(MainActivity.this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(8),dp(8),dp(8),dp(8));box.setBackgroundDrawable(bg(CARD,16));for(int i=0;i<values.size();i++){final int idx=i;Button b=button(values.get(i));b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setTextColor(i==selected?ACCENT:TEXT);sizePx(b,14);b.setBackgroundColor(Color.TRANSPARENT);box.addView(b,new LinearLayout.LayoutParams(dp(280),dp(48)));b.setOnClickListener(v->{selected=idx;setText(value());d.dismiss();if(listener!=null)listener.selected(this);});}ScrollView sc=new ScrollView(MainActivity.this);sc.addView(box);d.setContentView(sc,new ViewGroup.LayoutParams(dp(296),Math.min(dp(420),dp(16+48*values.size()))));Window w=d.getWindow();if(w!=null)w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));d.show();}
  }
  interface ToggleListener { void toggled(boolean value); }
  final class SkeletonToggle extends FrameLayout {View thumb;boolean checked;ToggleListener listener;SkeletonToggle(){super(MainActivity.this);setPadding(dp(3),dp(3),dp(3),dp(3));thumb=new View(MainActivity.this);thumb.setBackgroundDrawable(flat(Color.WHITE,99));addView(thumb,new FrameLayout.LayoutParams(dp(22),dp(22)));setChecked(false);setOnClickListener(v->{setChecked(!checked);if(listener!=null)listener.toggled(checked);});}void setOnToggle(ToggleListener l){listener=l;}void setChecked(boolean c){checked=c;setBackgroundDrawable(flat(c?ACCENT:Color.rgb(65,73,82),99));thumb.setTranslationX(c?dp(22):0);}boolean isChecked(){return checked;}}
  final class AspectFrame extends FrameLayout {float rw=2f,rh=3f;AspectFrame(Context c){super(c);}void ratio(float w,float h){rw=w;rh=h;requestLayout();}@Override protected void onMeasure(int ws,int hs){int aw=MeasureSpec.getSize(ws),ah=MeasureSpec.getSize(hs);int w=aw,h=(int)(w*rh/rw);if(h>ah){h=ah;w=(int)(h*rw/rh);}super.onMeasure(MeasureSpec.makeMeasureSpec(Math.max(1,w),MeasureSpec.EXACTLY),MeasureSpec.makeMeasureSpec(Math.max(1,h),MeasureSpec.EXACTLY));}}


  final class YoutubeDpad extends ViewGroup {
    Paint paint=new Paint(Paint.ANTI_ALIAS_FLAG),line=new Paint(Paint.ANTI_ALIAS_FLAG); View up,left,right,down,ok;
    YoutubeDpad(){super(MainActivity.this);setWillNotDraw(false);line.setColor(Color.rgb(74,86,96));line.setAlpha(90);line.setStrokeWidth(dp(1));}
    void bind(View u,View l,View r,View d,View o){up=u;left=l;right=r;down=d;ok=o;addView(u);addView(l);addView(r);addView(d);addView(o);}
    @Override protected void onMeasure(int ws,int hs){int w=MeasureSpec.getSize(ws),h=MeasureSpec.getSize(hs),d=Math.max(1,Math.min(w,h));setMeasuredDimension(d,d);measureExact(up,(int)(d*.50f),(int)(d*.32f));measureExact(down,(int)(d*.50f),(int)(d*.32f));measureExact(left,(int)(d*.32f),(int)(d*.50f));measureExact(right,(int)(d*.32f),(int)(d*.50f));measureExact(ok,(int)(d*.38f),(int)(d*.38f));}
    void measureExact(View v,int w,int h){v.measure(MeasureSpec.makeMeasureSpec(Math.max(1,w),MeasureSpec.EXACTLY),MeasureSpec.makeMeasureSpec(Math.max(1,h),MeasureSpec.EXACTLY));}
    @Override protected void onLayout(boolean c,int l,int t,int r,int b){int d=getMeasuredWidth();layoutAt(up,(int)(d*.25f),0);layoutAt(down,(int)(d*.25f),d-down.getMeasuredHeight());layoutAt(left,0,(int)(d*.25f));layoutAt(right,d-right.getMeasuredWidth(),(int)(d*.25f));layoutAt(ok,(d-ok.getMeasuredWidth())/2,(d-ok.getMeasuredHeight())/2);}
    void layoutAt(View v,int x,int y){v.layout(x,y,x+v.getMeasuredWidth(),y+v.getMeasuredHeight());}
    @Override protected void onDraw(Canvas c){super.onDraw(c);int d=getWidth();float cx=d/2f,cy=d/2f,r=d/2f-1;paint.setShader(new RadialGradient(cx,cy,r,new int[]{Color.rgb(52,60,68),Color.rgb(36,43,50),Color.rgb(22,27,32)},new float[]{0f,.59f,1f},Shader.TileMode.CLAMP));c.drawCircle(cx,cy,r,paint);paint.setShader(null);paint.setStyle(Paint.Style.STROKE);paint.setStrokeWidth(dp(1));paint.setColor(Color.rgb(60,70,80));c.drawCircle(cx,cy,r,paint);paint.setStyle(Paint.Style.FILL);float k=(float)(r/Math.sqrt(2));c.drawLine(cx-k,cy-k,cx+k,cy+k,line);c.drawLine(cx+k,cy-k,cx-k,cy+k,line);}
  }
  final class YoutubeNavPanel extends ViewGroup {
    ImageButton back,mute; YoutubeDpad dpad; int gapPx,sidePx,dpadPx;
    YoutubeNavPanel(ImageButton b,YoutubeDpad d,ImageButton m){super(MainActivity.this);back=b;dpad=d;mute=m;addView(back);addView(dpad);addView(mute);}
    @Override protected void onMeasure(int ws,int hs){int width=MeasureSpec.getSize(ws);float den=getResources().getDisplayMetrics().density;float screenDp=getResources().getDisplayMetrics().widthPixels/den,heightDp=getResources().getDisplayMetrics().heightPixels/den;int sideDp=52,gapDp=6;float vw=.72f;int capDp=292;if(heightDp<=780){sideDp=48;vw=.64f;capDp=250;}if(screenDp<=360){sideDp=46;gapDp=3;vw=.70f;capDp=244;}sidePx=dp(sideDp);gapPx=dp(gapDp);int target=(int)Math.min(dp(capDp),getResources().getDisplayMetrics().widthPixels*vw);int fit=Math.max(dp(132),width-2*sidePx-2*gapPx);dpadPx=Math.max(dp(132),Math.min(target,fit));measureExact(back,sidePx,sidePx);measureExact(mute,sidePx,sidePx);measureExact(dpad,dpadPx,dpadPx);setMeasuredDimension(width,dpadPx);}
    void measureExact(View v,int w,int h){v.measure(MeasureSpec.makeMeasureSpec(Math.max(1,w),MeasureSpec.EXACTLY),MeasureSpec.makeMeasureSpec(Math.max(1,h),MeasureSpec.EXACTLY));}
    @Override protected void onLayout(boolean c,int l,int t,int r,int b){int w=r-l,h=b-t;int total=sidePx+gapPx+dpadPx+gapPx+sidePx;int x=Math.max(0,(w-total)/2);int y=h-sidePx;back.layout(x,y,x+sidePx,y+sidePx);x+=sidePx+gapPx;dpad.layout(x,0,x+dpadPx,dpadPx);x+=dpadPx+gapPx;mute.layout(x,y,x+sidePx,y+sidePx);}
  }


  void buildApp(){
    root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
    content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));
    screens[0]=buildHome();screens[1]=buildVideo();screens[2]=buildSk();screens[3]=buildDevices();for(View v:screens){content.addView(v,new FrameLayout.LayoutParams(-1,-1));v.setVisibility(View.GONE);}screens[0].setVisibility(View.VISIBLE);
    nav=row();nav.setBackgroundColor(Color.argb(250,10,13,16));nav.setPadding(dp(10),dp(6),dp(10),dp(6));
    for(int i=0;i<4;i++){final int n=i;Button b=iconTextButton(NAV_NAMES[i],NAV_ICONS[i],21,9,i==0?ACCENT:MUTED);b.setLetterSpacing(-.005f);b.setOnClickListener(v->showScreen(n));navButtons[i]=b;nav.addView(b,new LinearLayout.LayoutParams(0,dp(58),1));styleNav(i,i==0);}
    root.addView(nav,new LinearLayout.LayoutParams(-1,dp(70)));setContentView(root);
  }
  LinearLayout header(String title){
    LinearLayout h=row();h.setPadding(dp(16),dp(12),dp(10),dp(8));h.setGravity(Gravity.CENTER_VERTICAL);
    LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);
    TextView a=tv(title,20,TEXT);weight(a,650);a.setLetterSpacing(-.015f);copy.addView(a,new LinearLayout.LayoutParams(-1,dp(27)));
    LinearLayout sub=row();conn=tv("Home Edge · Підключення…",11,MUTED);weight(conn,500);conn.setTag(title);connViews.add(conn);sub.addView(conn,new LinearLayout.LayoutParams(-2,dp(20)));View dot=new View(this);dot.setBackgroundDrawable(flat(GREEN,99));LinearLayout.LayoutParams dpv=new LinearLayout.LayoutParams(dp(6),dp(6));dpv.setMargins(dp(6),0,0,0);sub.addView(dot,dpv);copy.addView(sub,new LinearLayout.LayoutParams(-1,dp(20)));
    h.addView(copy,new LinearLayout.LayoutParams(0,dp(54),1));
    ImageView bulb=iconView("lightbulb-outline",21,Color.rgb(111,120,130));hyperionBulbs.add(bulb);h.addView(bulb,new LinearLayout.LayoutParams(dp(28),dp(40)));
    NativeSwitch sw=new NativeSwitch();hyperionSwitches.add(sw);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(42),dp(24));sp.setMargins(dp(3),0,dp(3),0);h.addView(sw,sp);
    ImageButton more=iconButton("dots-vertical",23,TEXT,40);more.setOnClickListener(v->showHeaderMenu(title));h.addView(more,new LinearLayout.LayoutParams(dp(40),dp(40)));
    pollHyperionHeader();return h;
  }
  View scrollWrap(LinearLayout body){ScrollView x=new ScrollView(this);x.setFillViewport(true);x.setClipToPadding(false);x.addView(body,new ScrollView.LayoutParams(-1,-2));return x;}

  View buildHome(){
    LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(BG);page.addView(header("Головна"),new LinearLayout.LayoutParams(-1,dp(74)));
    LinearLayout main=new LinearLayout(this);main.setOrientation(LinearLayout.VERTICAL);main.setPadding(dp(13),0,dp(13),0);page.addView(main,new LinearLayout.LayoutParams(-1,0,1));
    LinearLayout modes=row();modes.setGravity(Gravity.CENTER);String[] labels={"YouTube","Cast","TV","Games"},icons={"youtube","cast-connected","television","gamepad-variant"},targets={"kiosk","mpv","tv","games"};
    for(int i=0;i<4;i++){final String mode=targets[i];Button b=iconTextButton(labels[i],icons[i],22,10,MUTED);b.setOnClickListener(v->post("/api/mode/"+mode,new JSONObject(),(j,e)->pollHome()));modeButtons[i]=b;LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(64),1);if(i>0)lp.setMargins(dp(6),0,0,0);modes.addView(b,lp);}main.addView(modes,new LinearLayout.LayoutParams(-1,dp(64)));
    LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setBackgroundDrawable(bg(CARD,16));card.setPadding(dp(12),dp(10),dp(12),dp(12));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,0,1);cp.setMargins(0,dp(6),0,0);main.addView(card,cp);
    homeVisual=new FrameLayout(this);card.addView(homeVisual,new LinearLayout.LayoutParams(-1,0,1));
    homePoster=new AspectImageView(this);homePoster.ratio(2,3);homePoster.setBackgroundColor(Color.rgb(10,13,16));GradientDrawable pg=bg(Color.rgb(10,13,16),14);homePoster.setBackgroundDrawable(pg);FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(-1,-1,Gravity.CENTER);homeVisual.addView(homePoster,pp);
    homeTvPanel=new LinearLayout(this);homeTvPanel.setOrientation(LinearLayout.VERTICAL);homeTvPanel.setBackgroundColor(CARD);homeTvPanel.setVisibility(View.GONE);homeVisual.addView(homeTvPanel,new FrameLayout.LayoutParams(-1,-1));
    homeTitle=tv("Нічого не відтворюється",14,TEXT);weight(homeTitle,600);homeTitle.setGravity(Gravity.CENTER);homeTitle.setSingleLine(true);homeTitle.setEllipsize(TextUtils.TruncateAt.END);card.addView(homeTitle,new LinearLayout.LayoutParams(-1,dp(24)));
    homeMeta=tv("",11,MUTED);weight(homeMeta,500);homeMeta.setGravity(Gravity.CENTER);card.addView(homeMeta,new LinearLayout.LayoutParams(-1,dp(20)));
    homeYoutubePanel=buildYoutubePanel();homeYoutubePanel.setVisibility(View.GONE);card.addView(homeYoutubePanel,new LinearLayout.LayoutParams(-1,-2));
    homeTimeRow=row();homePos=tv("0:00",11,MUTED);homeDur=tv("0:00",11,MUTED);homeTimeRow.addView(homePos,new LinearLayout.LayoutParams(0,dp(19),1));homeDur.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);homeTimeRow.addView(homeDur,new LinearLayout.LayoutParams(0,dp(19),1));card.addView(homeTimeRow);
    homeSeek=new SkeletonSlider();homeSeek.setMax(1);card.addView(homeSeek,new LinearLayout.LayoutParams(-1,dp(22)));homeSeek.setOnValueListener(new SliderListener(){public void changed(int x,boolean from){if(from)setText(homePos,fmt(x));}public void stopped(int x){JSONObject o=new JSONObject();try{o.put("position",x);}catch(Exception e){}post("/api/seek",o,(j,e)->{});}});
    homeTransport=row();String[] ti={"rewind-15","play","fast-forward-15","volume-off"},ta={"back","toggle","forward","mute"};for(int i=0;i<4;i++){final String act=ta[i];ImageButton b=iconButton(ti[i],i==3?26:25,TEXT,48);if(i==1)b.setBackgroundDrawable(flat(ACCENT,99));b.setOnClickListener(v->{if(act.equals("mute"))toggleMute();else post("/api/control/"+act,new JSONObject(),(j,e)->pollHome());});transportButtons[i]=b;homeTransport.addView(b,new LinearLayout.LayoutParams(0,dp(48),1));}card.addView(homeTransport,new LinearLayout.LayoutParams(-1,dp(48)));
    LinearLayout vr=row();ImageButton vd=iconButton("volume-high",19,Color.rgb(232,235,238),40);vd.setAlpha(.72f);vd.setOnClickListener(v->stepVolume(-5));vr.addView(vd,new LinearLayout.LayoutParams(dp(40),dp(49)));LinearLayout vs=new LinearLayout(this);vs.setOrientation(LinearLayout.VERTICAL);homeVol=tv("0%",11,Color.rgb(238,241,243));homeVol.setGravity(Gravity.CENTER);vs.addView(homeVol,new LinearLayout.LayoutParams(-1,dp(18)));homeVolume=new SkeletonSlider();homeVolume.setMax(100);vs.addView(homeVolume,new LinearLayout.LayoutParams(-1,dp(31)));vr.addView(vs,new LinearLayout.LayoutParams(0,dp(49),1));ImageButton vu=iconButton("volume-high",27,Color.rgb(232,235,238),40);vu.setOnClickListener(v->stepVolume(5));vr.addView(vu,new LinearLayout.LayoutParams(dp(40),dp(49)));card.addView(vr,new LinearLayout.LayoutParams(-1,dp(49)));homeVolume.setOnValueListener(new SliderListener(){public void changed(int x,boolean from){if(from)setText(homeVol,x+"%");}public void stopped(int x){JSONObject o=new JSONObject();try{o.put("level",x);}catch(Exception e){}post("/api/volume",o,(j,e)->{});}});
    return page;
  }
  YoutubeNavPanel buildYoutubePanel(){
    ImageButton back=iconButton("keyboard-return",24,TEXT,52);GradientDrawable backBg=bg(Color.rgb(32,39,46),99);backBg.setShape(GradientDrawable.OVAL);back.setBackgroundDrawable(backBg);back.setOnClickListener(v->remote("back"));
    ImageButton mute=iconButton("volume-off",27,TEXT,52);GradientDrawable muteBg=bg(Color.rgb(32,39,46),99);muteBg.setShape(GradientDrawable.OVAL);mute.setBackgroundDrawable(muteBg);mute.setOnClickListener(v->toggleMute());
    YoutubeDpad d=new YoutubeDpad();String[] names={"chevron-up","chevron-left","chevron-right","chevron-down"},acts={"up","left","right","down"};View[] keys=new View[4];for(int i=0;i<4;i++){final String act=acts[i];ImageButton k=iconButton(names[i],29,TEXT,56);k.setBackgroundColor(Color.TRANSPARENT);k.setOnClickListener(v->remote(act));keys[i]=k;}
    Button ok=new Button(this);ok.setText("OK");sizePx(ok,15);weight(ok,800);ok.setTextColor(Color.WHITE);ok.setAllCaps(false);ok.setPadding(0,0,0,0);GradientDrawable okBg=bg(ACCENT,99);okBg.setShape(GradientDrawable.OVAL);ok.setBackgroundDrawable(okBg);ok.setOnClickListener(v->remote("ok"));d.bind(keys[0],keys[1],keys[2],keys[3],ok);
    return new YoutubeNavPanel(back,d,mute);
  }

  void stepVolume(int delta){get("/api/volume",(j,e)->{if(e!=null)return;int n=j.optInt("master",0);JSONObject o=new JSONObject();try{o.put("level",Math.max(0,Math.min(100,n+delta)));}catch(Exception x){}post("/api/volume",o,(a,b)->pollHome());});}


  View buildVideo(){
    LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(BG);page.addView(header("Відео"),new LinearLayout.LayoutParams(-1,dp(74)));
    LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(12),dp(14),dp(12),dp(12));body.setBackgroundDrawable(bg(CARD,16));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,0,1);bp.setMargins(dp(13),0,dp(13),0);page.addView(scrollWrap(body),bp);
    LinearLayout catalog=row();catalog.setGravity(Gravity.TOP);catalog.setBackgroundDrawable(bg(INPUT,13));catalog.setPadding(dp(11),dp(11),dp(11),dp(11));videoPoster=new AspectImageView(this);videoPoster.ratio(2,3);videoPoster.setBackgroundColor(BG);catalog.addView(videoPoster,new LinearLayout.LayoutParams(dp(78),dp(117)));LinearLayout copy=new LinearLayout(this);copy.setOrientation(LinearLayout.VERTICAL);copy.setPadding(dp(13),0,0,0);videoTitle=tv("Відео",15,TEXT);weight(videoTitle,600);copy.addView(videoTitle,new LinearLayout.LayoutParams(-1,dp(22)));videoMeta=tv("HOME EDGE",10,ACCENT);weight(videoMeta,750);copy.addView(videoMeta,new LinearLayout.LayoutParams(-1,dp(18)));videoOverview=tv("Вставте посилання, щоб знайти відео.",11,MUTED);videoOverview.setGravity(Gravity.TOP);videoOverview.setMaxLines(7);videoOverview.setEllipsize(TextUtils.TruncateAt.END);copy.addView(videoOverview,new LinearLayout.LayoutParams(-1,0,1));catalog.addView(copy,new LinearLayout.LayoutParams(0,dp(126),1));body.addView(catalog,new LinearLayout.LayoutParams(-1,dp(148)));
    LinearLayout selectors=new LinearLayout(this);selectors.setOrientation(LinearLayout.VERTICAL);selectors.setPadding(0,dp(16),0,0);historyBtn=selectorButton("Історія","history");historyBtn.setOnClickListener(v->showHistoryDialog());selectors.addView(historyBtn,new LinearLayout.LayoutParams(-1,dp(56)));
    seasonSp=select();episodeSp=select();qualitySp=select();voiceSp=select();selectors.addView(selectorRow("Сезон","playlist-play",seasonSp));selectors.addView(selectorRow("Серія","playlist-play",episodeSp));selectors.addView(selectorRow("Якість","quality-high",qualitySp));selectors.addView(selectorRow("Доріжка","account-voice",voiceSp));body.addView(selectors);
    SelectListener sl=v->{if(!spinnerBusy)updateVideoSelectors(v);};seasonSp.setOnSelected(sl);episodeSp.setOnSelected(sl);qualitySp.setOnSelected(sl);voiceSp.setOnSelected(sl);
    providerRow=row();providerRow.setGravity(Gravity.CENTER);providerRow.setVisibility(View.GONE);traktBtn=providerButton("Trakt");moviebaseBtn=providerButton("Moviebase");traktBtn.setOnClickListener(v->openProvider(true));moviebaseBtn.setOnClickListener(v->openProvider(false));providerRow.addView(traktBtn,new LinearLayout.LayoutParams(dp(58),dp(58)));Space pg=new Space(this);providerRow.addView(pg,new LinearLayout.LayoutParams(dp(18),1));providerRow.addView(moviebaseBtn,new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(66));pp.setMargins(0,dp(6),0,dp(4));body.addView(providerRow,pp);
    LinearLayout actions=row();actions.setGravity(Gravity.CENTER_VERTICAL);applyBtn=button("");applyBtn.setBackgroundDrawable(flat(ACCENT,15));applyBtn.setCompoundDrawables(null,null,null,null);applyBtn.setForeground(icon("play",25,Color.WHITE));applyBtn.setOnClickListener(v->applyVideo());resetBtn=button("");resetBtn.setBackgroundDrawable(bg(ACTION,15));resetBtn.setForeground(icon("refresh",25,Color.rgb(231,235,238)));resetBtn.setOnClickListener(v->resetVideo());actions.addView(applyBtn,new LinearLayout.LayoutParams(dp(56),dp(50)));Space gap=new Space(this);actions.addView(gap,new LinearLayout.LayoutParams(dp(10),1));actions.addView(resetBtn,new LinearLayout.LayoutParams(dp(56),dp(50)));Space flex=new Space(this);actions.addView(flex,new LinearLayout.LayoutParams(0,1,1));LinearLayout autoBox=row();autoBox.setGravity(Gravity.CENTER);autoBox.setBackgroundDrawable(bg(ACTION,15));autoBox.setPadding(dp(10),0,dp(10),0);ImageView ai=iconView("autoplay-repeat",24,MUTED);autoBox.addView(ai,new LinearLayout.LayoutParams(dp(28),dp(50)));autoplay=new SkeletonToggle();autoplay.setOnToggle(c->{JSONObject o=new JSONObject();try{o.put("enabled",c);}catch(Exception e){}put("/api/video/autoplay",o,(j,e)->{});});autoBox.addView(autoplay,new LinearLayout.LayoutParams(dp(50),dp(28)));actions.addView(autoBox,new LinearLayout.LayoutParams(dp(118),dp(50)));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(50));body.addView(actions,ap);
    videoMsg=tv("",11,MUTED);body.addView(videoMsg,new LinearLayout.LayoutParams(-1,dp(20)));return page;
  }
  SkeletonSelect select(){return new SkeletonSelect();}
  View selectorRow(String label,String iconName,SkeletonSelect spin){LinearLayout r=row();r.setGravity(Gravity.BOTTOM);ImageView iv=iconView(iconName,20,Color.rgb(216,221,226));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(dp(28),dp(39));ip.setMargins(0,0,dp(8),0);r.addView(iv,ip);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);TextView l=tv(label,10,Color.rgb(196,202,208));box.addView(l,new LinearLayout.LayoutParams(-1,dp(17)));box.addView(spin,new LinearLayout.LayoutParams(-1,dp(39)));r.addView(box,new LinearLayout.LayoutParams(0,dp(56),1));return r;}
  Button selectorButton(String label,String iconName){Button b=iconTextButton(label,iconName,20,14,TEXT);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setCompoundDrawablePadding(dp(16));b.setBackgroundDrawable(bg(INPUT,9));b.setPadding(0,0,dp(10),0);return b;}
  ImageButton providerButton(String label){ImageButton b=new ImageButton(this);b.setContentDescription(label);b.setScaleType(ImageView.ScaleType.CENTER_CROP);b.setPadding(dp(4),dp(4),dp(4),dp(4));GradientDrawable g=bg(ACTION,99);g.setShape(GradientDrawable.OVAL);b.setBackgroundDrawable(g);return b;}


  View buildSk(){LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(BG);page.addView(header("СК"),new LinearLayout.LayoutParams(-1,dp(74)));skList=new LinearLayout(this);skList.setOrientation(LinearLayout.VERTICAL);skList.setPadding(dp(13),0,dp(13),dp(18));page.addView(scrollWrap(skList),new LinearLayout.LayoutParams(-1,0,1));return page;}
  void pollSk(){if(server==null)return;get("/api/native/skeleton-dashboard",(j,e)->{if(e!=null)return;String key=j.toString();if(key.equals(skSnapshot))return;skSnapshot=key;JSONArray a=j.optJSONArray("cards");if(a==null)return;skList.removeAllViews();for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x==null)continue;LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackgroundDrawable(bg(CARD,16));c.setPadding(dp(12),dp(12),dp(12),dp(12));LinearLayout head=row();String level=x.optString("level","ok");int col="attention".equals(level)?ACCENT:GREEN;ImageView iv=iconView(x.optString("icon","monitor-dashboard"),21,col);head.addView(iv,new LinearLayout.LayoutParams(dp(28),dp(28)));TextView title=tv(x.optString("title","Skeleton"),14,TEXT);weight(title,650);head.addView(title,new LinearLayout.LayoutParams(0,dp(28),1));View dot=new View(this);dot.setBackgroundDrawable(flat(col,99));head.addView(dot,new LinearLayout.LayoutParams(dp(7),dp(7)));c.addView(head,new LinearLayout.LayoutParams(-1,dp(30)));TextView text=tv(x.optString("text",""),12,MUTED);text.setGravity(Gravity.TOP);text.setLineSpacing(0,1.12f);c.addView(text,new LinearLayout.LayoutParams(-1,-2));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(10),0,0);skList.addView(c,lp);}});}


  View buildDevices(){LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(BG);page.addView(header("Пристрої"),new LinearLayout.LayoutParams(-1,dp(74)));devicesList=new LinearLayout(this);devicesList.setOrientation(LinearLayout.VERTICAL);devicesList.setPadding(dp(13),0,dp(13),dp(18));page.addView(scrollWrap(devicesList),new LinearLayout.LayoutParams(-1,0,1));return page;}


  void showScreen(int n){if(n==current&&screens[n].getVisibility()==View.VISIBLE)return;for(int i=0;i<4;i++){screens[i].setVisibility(i==n?View.VISIBLE:View.GONE);styleNav(i,i==n);}current=n;if(poller!=null)ui.removeCallbacks(poller);if(n==1)loadVideo();else if(n==2)pollSk();else if(n==3)pollDevices();else if(n==0)pollHome();schedulePoll(100);}
  void schedulePoll(long delay){if(!resumed)return;if(poller!=null)ui.removeCallbacks(poller);poller=()->{if(!resumed)return;if(current==0)pollHome();else if(current==2)pollSk();else if(current==3)pollDevices();schedulePoll(current==0?2500:current==2?10000:current==3?15000:30000);};ui.postDelayed(poller,delay);}

  void pollHyperionHeader(){if(server==null)return;get("/api/hyperion",(j,e)->{if(e!=null)return;boolean on=j.optBoolean("enabled");hyperionOn=on;for(ImageView b:hyperionBulbs)b.setImageDrawable(icon(on?"lightbulb-on-outline":"lightbulb-outline",21,on?ACCENT:Color.rgb(111,120,130)));for(NativeSwitch x:hyperionSwitches)x.setChecked(on);});}
  void setHyperion(boolean on){if(hyperionBusy)return;hyperionBusy=true;JSONObject o=new JSONObject();try{o.put("enabled",on);}catch(Exception e){}post("/api/hyperion",o,(j,e)->{hyperionBusy=false;if(e==null)pollHyperionHeader();});}
  void showHeaderMenu(String title){final Dialog d=new Dialog(this);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(7),dp(7),dp(7),dp(7));b.setBackgroundDrawable(bg(Color.rgb(23,27,32),16));String[][] items={{"television","Редагувати канали"},{"monitor-dashboard","Скрінсейвер"},{"information-outline","Інфо"}};for(String[] it:items){Button x=iconTextButton(it[1],it[0],23,14,TEXT);x.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);x.setCompoundDrawablePadding(dp(12));x.setPadding(dp(13),0,dp(13),0);if(it[1].equals("Інфо"))x.setOnClickListener(v->{d.dismiss();showInfo();});else x.setEnabled(false);b.addView(x,new LinearLayout.LayoutParams(dp(240),dp(48)));}d.setContentView(b);Window w=d.getWindow();if(w!=null)w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));d.show();}
  void showInfo(){new AlertDialog.Builder(this).setTitle("Home").setMessage("Версія застосунку "+VERSION+"\nSkeleton Home Edge").setPositiveButton("OK",null).show();}
  void discover(){net.execute(()->{String found=null;for(String s:SERVERS){try{HttpURLConnection c=(HttpURLConnection)new URL(s+"/health").openConnection();c.setConnectTimeout(1800);c.setReadTimeout(1800);if(c.getResponseCode()/100==2){found=s;c.disconnect();break;}c.disconnect();}catch(Exception e){}}final String f=found;ui.post(()->{server=f;for(TextView cv:connViews){boolean sk="СК".equals(String.valueOf(cv.getTag()));setText(cv,f==null?(sk?"Skeleton · Недоступно":"Home Edge · Недоступно"):(sk?"Skeleton · Підключено ●":"Home Edge · Підключено ●"));}if(f!=null){get("/api/ui/build?native="+VERSION,(j,e)->{});if(current==0)pollHome();else if(current==1)loadVideo();else if(current==2)pollSk();else if(current==3)pollDevices();}});});}
  JSONObject req(String method,String path,JSONObject body)throws Exception{if(server==null)throw new IOException("no server");HttpURLConnection c=(HttpURLConnection)new URL(server+path).openConnection();c.setConnectTimeout(3500);c.setReadTimeout(9000);c.setRequestMethod(method);c.setRequestProperty("Accept","application/json");if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");OutputStream o=c.getOutputStream();o.write(body.toString().getBytes("UTF-8"));o.close();}int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();StringBuilder sb=new StringBuilder();if(in!=null){BufferedReader r=new BufferedReader(new InputStreamReader(in,"UTF-8"));String line;while((line=r.readLine())!=null)sb.append(line);r.close();}c.disconnect();JSONObject j=sb.length()>0?new JSONObject(sb.toString()):new JSONObject();if(code>=400)throw new IOException(j.optString("error","HTTP "+code));return j;}
  void call(String method,String path,JSONObject body,JsonCb cb){if(server==null){discover();if(cb!=null)ui.post(()->cb.done(null,new IOException("Home Edge недоступний")));return;}net.execute(()->{try{JSONObject j=req(method,path,body);ui.post(()->{if(cb!=null)cb.done(j,null);});}catch(Exception e){ui.post(()->{if(cb!=null)cb.done(null,e);});}});}
  void get(String p,JsonCb c){call("GET",p,null,c);}void post(String p,JSONObject o,JsonCb c){call("POST",p,o,c);}void put(String p,JSONObject o,JsonCb c){call("PUT",p,o,c);}void del(String p,JsonCb c){call("DELETE",p,null,c);}

  void pollHome(){if(server==null)return;get("/api/mode",(m,e)->{if(e!=null)return;get("/api/player",(p,e2)->{if(e2!=null)return;get("/api/volume",(v,e3)->{if(e3==null)renderHome(m,p,v);});});});}
  void renderHome(JSONObject m,JSONObject p,JSONObject v){String key=m.toString()+"|"+p.optBoolean("pause")+"|"+p.optString("display-title")+"|"+(int)p.optDouble("time-pos")+"|"+(int)p.optDouble("duration")+"|"+v.optInt("master")+"|"+p.optString("poster_landscape")+"|"+p.optString("poster");if(key.equals(homeSnapshot))return;homeSnapshot=key;String mode=m.optString("mode",m.optString("tv_mode",""));String[] mm={"kiosk","mpv","tv","games"},mi={"youtube","cast-connected","television","gamepad-variant"};for(int i=0;i<4;i++){boolean a=mm[i].equals(mode);modeButtons[i].setTextColor(a?ACCENT:MUTED);weight(modeButtons[i],a?700:600);modeButtons[i].setCompoundDrawables(null,icon(mi[i],22,a?ACCENT:MUTED),null,null);}currentHomeMode=mode;boolean youtube=mode.equals("kiosk"),tv=mode.equals("tv");homePoster.ratio(youtube?16:2,youtube?9:3);homeYoutubePanel.setVisibility(youtube?View.VISIBLE:View.GONE);if(youtube)homeYoutubePanel.requestLayout();homeTvPanel.setVisibility(tv?View.VISIBLE:View.GONE);homeVisual.setVisibility(View.VISIBLE);homeTransport.setVisibility(youtube?View.GONE:View.VISIBLE);for(int i=0;i<4;i++)if(transportButtons[i]!=null)transportButtons[i].setVisibility(tv&&i<3?View.GONE:View.VISIBLE);homeTimeRow.setVisibility(tv?View.GONE:View.VISIBLE);homeSeek.setVisibility(tv?View.GONE:View.VISIBLE);if(tv)loadNativeTvChannels();boolean run=p.optBoolean("running");String title=run?opt(p,"display-title",opt(p,"media-title","Відео")):"Нічого не відтворюється";setText(homeTitle,title);String meta="";if(run&&p.has("season")){String se="S"+p.optString("season","");String ep=p.optString("episode","").replaceAll("[^0-9]","");if(ep.length()>0)se+=" · E"+ep;meta=se;}setText(homeMeta,meta);homeMeta.setTextColor(meta.length()>0?ACCENT:MUTED);homeMeta.setVisibility(meta.length()>0?View.VISIBLE:View.GONE);int d=(int)p.optDouble("duration",0),t=(int)p.optDouble("time-pos",0);homeSeek.setMax(Math.max(1,d));if(!homeSeek.isPressed())homeSeek.setProgress(Math.min(t,d));setText(homePos,fmt(t));setText(homeDur,fmt(d));int vol=v.optInt("master",0);if(!homeVolume.isPressed())homeVolume.setProgress(vol);setText(homeVol,vol+"%");String poster="kiosk".equals(currentHomeMode)?p.optString("poster_landscape",p.optString("poster","")):p.optString("poster",p.optString("poster_landscape",""));loadImage(homePoster,poster,"kiosk".equals(currentHomeMode));}
  void loadNativeTvChannels(){if(server==null)return;get("/api/tv/channels",(j,e)->{if(e!=null||!"tv".equals(currentHomeMode))return;JSONArray a=j.optJSONArray("channels");if(a==null)return;homeTvPanel.removeAllViews();int count=Math.min(7,a.length());for(int i=0;i<count;i++){JSONObject c=a.optJSONObject(i);if(c==null)continue;Button r=new Button(this);String name=c.optString("display_name",c.optString("name","Канал"));String prog=c.optString("programme_title","");r.setText(prog.length()>0?name+"\n"+prog:name);r.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);r.setTextColor(MUTED);sizePx(r,prog.length()>0?10:13);weight(r,650);r.setAllCaps(false);r.setBackgroundColor(Color.TRANSPARENT);final String id=c.optString("channel_id","");r.setOnClickListener(v->{JSONObject o=new JSONObject();try{o.put("channel_id",id);}catch(Exception x){}post("/api/tv/play",o,(x,er)->pollHome());});homeTvPanel.addView(r,new LinearLayout.LayoutParams(-1,0,1));}});}
  void remote(String a){JSONObject o=new JSONObject();try{o.put("action",a);o.put("phase","tap");}catch(Exception e){}post("/api/remote/control",o,(j,e)->{});}void toggleMute(){get("/api/volume",(j,e)->{if(e!=null)return;int n=j.optInt("master",0);int target=n==0?Math.max(1,j.optInt("last_nonzero",25)):0;JSONObject o=new JSONObject();try{o.put("level",target);}catch(Exception x){}post("/api/volume",o,(a,b)->pollHome());});}

  void loadVideo(){if(server==null)return;get("/api/video/history",(h,e)->{if(e==null)videoHistory=h.optJSONArray("items");});get("/api/video/autoplay",(a,e)->{if(e==null){autoplay.setChecked(a.optBoolean("enabled"));}});get("/api/video/selection",(s,e)->{if(e!=null)return;videoSelection=s;currentJob=s.optString("job_id","");if(currentJob.length()>0)loadJob(currentJob);else renderVideoEmpty();});}
  JSONArray videoHistory=new JSONArray();
  void renderVideoEmpty(){setText(videoTitle,"Оберіть збережений твір");setText(videoMeta,"");setText(videoOverview,"Надішліть посилання через «Поділитися» або виберіть твір з історії.");providerRow.setVisibility(View.GONE);fill(seasonSp,new ArrayList<String>());fill(episodeSp,new ArrayList<String>());fill(qualitySp,new ArrayList<String>());fill(voiceSp,new ArrayList<String>());}
  void loadJob(String id){currentJob=id;get("/api/jobs/"+id,(j,e)->{if(e!=null){setText(videoMsg,"Home Edge недоступний");return;}videoJob=j;String st=j.optString("status","");if(st.equals("resolving")||st.equals("discovering")||st.equals("identified")||st.equals("cached_mapping_checked")||st.equals("searching_sources")||st.equals("candidates_found")){setText(videoMsg,"Шукаю перевірені джерела…");ui.postDelayed(()->{if(currentJob.equals(id))loadJob(id);},700);return;}videoSources=j.optJSONArray("sources");if(videoSources==null)videoSources=new JSONArray();renderVideoJob();});}
  void renderVideoJob(){JSONObject c=videoJob.optJSONObject("catalog");if(c==null)c=new JSONObject();setText(videoTitle,opt(c,"title",opt(videoJob,"title","Відео")));setText(videoMeta,(c.optString("content_type","")+" · "+c.optString("year","")).replaceAll("^ · | · $",""));setText(videoOverview,opt(c,"overview",""));String poster=c.optString("poster","");JSONObject sp=c.optJSONObject("season_posters");String prefSeason=videoSelection==null?"":videoSelection.optString("season","");if(sp!=null&&prefSeason.length()>0)poster=sp.optString(prefSeason,poster);loadImage(videoPoster,poster,false);updateSelectorsFromSources();loadExternalButtons();setText(videoMsg,videoSources.length()+" варіантів");}
  List<String> uniq(String key,String... filters){TreeSet<String> set=new TreeSet<String>(new Comparator<String>(){public int compare(String a,String b){int aa=num(a),bb=num(b);if(aa!=bb)return aa-bb;return a.compareTo(b);}});for(int i=0;i<videoSources.length();i++){JSONObject s=videoSources.optJSONObject(i);if(s==null||!match(s,filters))continue;String x=s.optString(key,"");if(x.length()>0)set.add(x);}return new ArrayList<String>(set);}int num(String x){Matcher m=Pattern.compile("(\\d+)").matcher(x==null?"":x);return m.find()?Integer.parseInt(m.group(1)):999999;}boolean match(JSONObject s,String... f){for(int i=0;i+1<f.length;i+=2)if(f[i+1]!=null&&f[i+1].length()>0&&!f[i+1].equals(s.optString(f[i],"")))return false;return true;}
  void updateSelectorsFromSources(){spinnerBusy=true;String ps=videoSelection==null?"":videoSelection.optString("season","");String pe=videoSelection==null?"":videoSelection.optString("episode","");String pv=videoSelection==null?"":videoSelection.optString("voice","");String pq="";String sid=videoSelection==null?"":videoSelection.optString("source_id","");for(int i=0;i<videoSources.length();i++){JSONObject s=videoSources.optJSONObject(i);if(s!=null&&sid.equals(s.optString("source_id"))){ps=s.optString("season",ps);pe=s.optString("episode",pe);pv=s.optString("translation",s.optString("group",pv));pq=s.optString("quality","");break;}}fillSelect(seasonSp,uniq("season"),ps);fillSelect(episodeSp,uniq("episode","season",sel(seasonSp)),pe);fillSelect(qualitySp,uniq("quality","season",sel(seasonSp),"episode",sel(episodeSp)),pq);fillSelect(voiceSp,voicesFor(sel(seasonSp),sel(episodeSp),sel(qualitySp)),pv);spinnerBusy=false;}
  List<String> voicesFor(String s,String e,String q){TreeSet<String> set=new TreeSet<String>();for(int i=0;i<videoSources.length();i++){JSONObject x=videoSources.optJSONObject(i);if(x==null||!match(x,"season",s,"episode",e,"quality",q))continue;String v=x.optString("translation",x.optString("group",""));if(v.length()>0)set.add(v);}return new ArrayList<String>(set);}
  void updateVideoSelectors(SkeletonSelect who){spinnerBusy=true;if(who==seasonSp){fillSelect(episodeSp,uniq("episode","season",sel(seasonSp)),"");fillSelect(qualitySp,uniq("quality","season",sel(seasonSp),"episode",sel(episodeSp)),"");fillSelect(voiceSp,voicesFor(sel(seasonSp),sel(episodeSp),sel(qualitySp)),"");}else if(who==episodeSp){fillSelect(qualitySp,uniq("quality","season",sel(seasonSp),"episode",sel(episodeSp)),"");fillSelect(voiceSp,voicesFor(sel(seasonSp),sel(episodeSp),sel(qualitySp)),"");}else if(who==qualitySp){fillSelect(voiceSp,voicesFor(sel(seasonSp),sel(episodeSp),sel(qualitySp)),"");}spinnerBusy=false;updateSeasonPoster();}
  void updateSeasonPoster(){JSONObject c=videoJob==null?null:videoJob.optJSONObject("catalog");if(c==null)return;String p=c.optString("poster","");JSONObject ss=c.optJSONObject("season_posters");if(ss!=null)p=ss.optString(sel(seasonSp),p);loadImage(videoPoster,p,false);}
  String sel(SkeletonSelect s){return s.value();}void fill(SkeletonSelect s,List<String> vals){s.setOptions(vals,"");}void fillSelect(SkeletonSelect s,List<String> vals,String wanted){s.setOptions(vals,wanted);}
  JSONObject selectedSource(){String se=sel(seasonSp),ep=sel(episodeSp),q=sel(qualitySp),v=sel(voiceSp);for(int i=0;i<videoSources.length();i++){JSONObject x=videoSources.optJSONObject(i);if(x==null)continue;String vv=x.optString("translation",x.optString("group",""));if(match(x,"season",se,"episode",ep,"quality",q)&&vv.equals(v))return x;}return null;}
  void applyVideo(){JSONObject s=selectedSource();if(s==null){toast("Оберіть варіант");return;}JSONObject o=new JSONObject();try{o.put("job_id",currentJob);o.put("source_id",s.optString("source_id"));o.put("season",s.optString("season"));o.put("episode",s.optString("episode"));o.put("voice",s.optString("translation",s.optString("group")));o.put("quality",s.optString("quality"));o.put("subtitles","off");}catch(Exception e){}post("/api/play",o,(j,e)->{if(e!=null){toast(e.getMessage());return;}toast("Застосовано");writeSelection(s);showScreen(0);});}
  void writeSelection(JSONObject s){JSONObject o=new JSONObject();try{o.put("job_id",currentJob);o.put("locked",true);o.put("url",videoJob.optString("page_url"));o.put("voice",s.optString("translation",s.optString("group")));o.put("season",s.optString("season"));o.put("episode",s.optString("episode"));o.put("source_id",s.optString("source_id"));o.put("title",opt(videoJob,"title",""));}catch(Exception e){}put("/api/video/selection",o,(j,e)->{});}
  void resetVideo(){del("/api/video/selection",(j,e)->{currentJob="";videoJob=null;videoSources=new JSONArray();videoSelection=new JSONObject();renderVideoEmpty();toast("Скинуто");});}
  void showHistoryDialog(){if(videoHistory==null||videoHistory.length()==0){toast("Історія порожня");return;}final ArrayList<JSONObject> all=new ArrayList<JSONObject>();for(int i=0;i<videoHistory.length();i++){JSONObject x=videoHistory.optJSONObject(i);if(x!=null)all.add(x);}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText search=new EditText(this);search.setHint("Знайти твір");search.setTextColor(TEXT);search.setHintTextColor(MUTED);box.addView(search,new LinearLayout.LayoutParams(-1,dp(52)));ListView list=new ListView(this);box.addView(list,new LinearLayout.LayoutParams(-1,dp(420)));final ArrayList<JSONObject> shown=new ArrayList<JSONObject>();final ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,new ArrayList<String>());list.setAdapter(ad);final Runnable render=()->{String q=search.getText().toString().toLowerCase(Locale.getDefault());shown.clear();ad.clear();for(JSONObject x:all){String t=x.optString("title","")+" "+x.optString("year","")+" "+x.optString("overview","");if(q.length()==0||t.toLowerCase(Locale.getDefault()).contains(q)){shown.add(x);ad.add(x.optString("title")+(x.optInt("year",0)>0?" · "+x.optInt("year"):""));}}ad.notifyDataSetChanged();};render.run();AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Історія").setView(box).setNegativeButton("Закрити",null).create();list.setOnItemClickListener((p,v,pos,id)->{JSONObject x=shown.get(pos);dlg.dismiss();openHistory(x);});search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){render.run();}public void afterTextChanged(Editable e){}});dlg.show();}
  void openHistory(JSONObject x){String hid=x.optString("history_id","");JSONObject o=new JSONObject();try{o.put("history_id",hid);}catch(Exception e){}post("/api/video/history/open",o,(j,e)->{if(e!=null){toast("Не вдалося відкрити");return;}historyBtn.setText(x.optString("title","Історія"));videoSelection=j.optJSONObject("preferred");if(videoSelection==null)videoSelection=new JSONObject();currentJob=j.optString("job_id","");try{videoSelection.put("job_id",currentJob);}catch(Exception z){}loadJob(currentJob);});}
  void loadExternalButtons(){if(currentJob.length()==0){providerRow.setVisibility(View.GONE);return;}get("/api/video/external-links?job_id="+Uri.encode(currentJob),(j,e)->{if(e!=null)return;providerRow.setTag(j);boolean t=j.optString("trakt_url","").length()>0, m=j.optInt("tmdb_id",0)>0||j.optString("imdb_id","").length()>0;traktBtn.setVisibility(t?View.VISIBLE:View.GONE);moviebaseBtn.setVisibility(m?View.VISIBLE:View.GONE);providerRow.setVisibility(t||m?View.VISIBLE:View.GONE);setAppIcon(traktBtn,findPackage("Trakt",new String[]{"tv.trakt.trakt","com.trakt.android"}));setAppIcon(moviebaseBtn,findPackage("Moviebase",new String[]{"com.moviebase"}));});}
  String findPackage(String label,String[] candidates){PackageManager pm=getPackageManager();for(String p:candidates)try{pm.getApplicationInfo(p,0);return p;}catch(Exception e){}try{List<ApplicationInfo> apps=pm.getInstalledApplications(0);for(ApplicationInfo a:apps){String l=String.valueOf(pm.getApplicationLabel(a));if(l.toLowerCase(Locale.US).contains(label.toLowerCase(Locale.US)))return a.packageName;}}catch(Exception e){}return null;}
  void setAppIcon(ImageButton b,String pkg){if(pkg==null)return;try{b.setImageDrawable(getPackageManager().getApplicationIcon(pkg));}catch(Exception e){}}
  void openProvider(boolean trakt){Object tag=providerRow.getTag();if(!(tag instanceof JSONObject))return;JSONObject x=(JSONObject)tag;String pkg=findPackage(trakt?"Trakt":"Moviebase",trakt?new String[]{"tv.trakt.trakt","com.trakt.android"}:new String[]{"com.moviebase"});if(pkg==null){toast((trakt?"Trakt":"Moviebase")+" не встановлено");return;}ArrayList<String> uris=new ArrayList<String>();if(trakt){String u=x.optString("trakt_url","");if(u.length()>0){uris.add(u.replace("https://app.trakt.tv/","https://trakt.tv/"));uris.add(u);String path=u.replaceFirst("https?://[^/]+/","");uris.add("trakt://"+path);}}else{int id=x.optInt("tmdb_id",0);String typ=videoJob!=null&&videoJob.optJSONObject("catalog")!=null?videoJob.optJSONObject("catalog").optString("media_type","movie"):"movie";if(id>0){uris.add("moviebase://"+typ+"/"+id);uris.add("moviebase://details/"+typ+"/"+id);uris.add("moviebase://tmdb/"+id);uris.add("https://moviebase.app/"+typ+"/"+id);}}PackageManager pm=getPackageManager();for(String u:uris){try{Intent in=new Intent(Intent.ACTION_VIEW,Uri.parse(u));in.setPackage(pkg);if(in.resolveActivity(pm)!=null){startActivity(in);return;}}catch(Exception e){}}Intent launch=pm.getLaunchIntentForPackage(pkg);if(launch!=null){int id=x.optInt("tmdb_id",0);launch.putExtra("tmdb_id",id);launch.putExtra("id",id);launch.putExtra("media_type",videoJob!=null&&videoJob.optJSONObject("catalog")!=null?videoJob.optJSONObject("catalog").optString("media_type","movie"):"movie");startActivity(launch);toast("Застосунок відкрито; deep-link твору не зареєстрований");}else toast("Не вдалося відкрити застосунок");}

  void pollDevices(){if(server==null)return;get("/api/native/devices",(j,e)->{if(e!=null)return;JSONArray a=j.optJSONArray("items");if(a==null)return;String key=a.toString();if(key.equals(devicesSnapshot))return;devicesSnapshot=key;devicesList.removeAllViews();for(int i=0;i<a.length();i++){JSONObject d=a.optJSONObject(i);if(d==null)continue;LinearLayout c=row();c.setGravity(Gravity.CENTER_VERTICAL);c.setBackgroundDrawable(bg(CARD,16));c.setPadding(dp(18),dp(14),dp(14),dp(14));ImageView iv=iconView("devices",34,TEXT);c.addView(iv,new LinearLayout.LayoutParams(dp(42),dp(44)));LinearLayout cp=new LinearLayout(this);cp.setOrientation(LinearLayout.VERTICAL);TextView n=tv(d.optString("name",d.optString("device_id")),17,TEXT);weight(n,650);cp.addView(n,new LinearLayout.LayoutParams(-1,dp(24)));Object on=d.opt("online");String st=on==JSONObject.NULL||on==null?"Стан не опитаний":(d.optBoolean("online")?"Онлайн":"Офлайн");TextView m=tv(st,11,MUTED);cp.addView(m,new LinearLayout.LayoutParams(-1,dp(20)));LinearLayout.LayoutParams cl=new LinearLayout.LayoutParams(0,dp(48),1);cl.setMargins(dp(13),0,0,0);c.addView(cp,cl);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(76));p.setMargins(0,dp(10),0,0);devicesList.addView(c,p);}});}


  void loadImage(ImageView view,String path,boolean landscape){if(path==null||path.length()==0){view.setImageDrawable(null);return;}String key=(String)view.getTag();if(path.equals(key))return;view.setTag(path);final String url=path.startsWith("http")?path:(server==null?"":server+path);if(url.length()==0)return;net.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(3000);c.setReadTimeout(5000);Bitmap bm=BitmapFactory.decodeStream(c.getInputStream());c.disconnect();ui.post(()->{if(path.equals(view.getTag())&&bm!=null)view.setImageBitmap(bm);});}catch(Exception e){}});}
  void handleIntent(Intent i){if(i==null||!Intent.ACTION_SEND.equals(i.getAction()))return;String text=i.getStringExtra(Intent.EXTRA_TEXT);if(text==null)return;Matcher m=Pattern.compile("https?://\\S+").matcher(text);if(!m.find())return;final String url=m.group();Runnable work=()->{JSONObject o=new JSONObject();try{o.put("url",url);}catch(Exception e){}post("/api/share",o,(j,e)->{if(e!=null){toast("Не вдалося відкрити посилання");return;}currentJob=j.optString("job_id","");videoSelection=new JSONObject();showScreen(1);loadJob(currentJob);});};if(server==null)ui.postDelayed(work,2200);else work.run();}
  void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
}
